apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-rabbitmq
  namespace: rabbitmq
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: rabbit-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rabbit-secret
