apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-rabbitmq
namespace: rabbitmq

resources:
- configmap-rabbitmq.yaml
- extsecret-rabbitmq-password.yaml
- rbac-rabbitmq.yaml
- statefulset-rabbitmq.yaml