apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: redis
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: config
        image: redis:6.2
        command: [ "bash", "-c" ]
        args:
          - |
            #nodes=(redis-0.redis.redis.svc.cluster.local redis-1.redis.redis.svc.cluster.local redis-2.redis.redis.svc.cluster.local)
            replicas=1

            function svrname() {
              let id=$1-1
              echo "redis-$id.redis.redis.svc.cluster.local"
            }

            if [ $replicas -gt 1 ]; then
              for cnt in `seq 1 1 $replicas`
              do
                  i=$(svrname $cnt)
                  echo "finding master at $i"
                  MASTER=$(redis-cli --no-auth-warning --raw -h $i -a $REDIS_PASSWORD info replication | awk '{print $1}' | grep master_host: | cut -d ":" -f2)
                  ROLECHECK=$(redis-cli --no-auth-warning --raw -h $i -a $REDIS_PASSWORD info replication | awk '{print $1}' | grep role: | cut -d ":" -f2)
                  if [ "$ROLECHECK" == "master" ]; then
                      echo "found master $i"
                      MASTER=$i
                      break
                  fi
                  if [ "$MASTER" == "" ] && [ $ROLECHECK != "master" ]; then
                      echo "no master found"
                      MASTER=
                  else
                      echo "found $MASTER"
                      break
                  fi
              done
              if [ "$MASTER" == "" ]; then
                  echo "no master found, exiting as redis might not be up yet"
                  exit 1
              fi
            else
              MASTER=$(svrname 1)
            fi
            echo "sentinel monitor master $MASTER 6379 2" >> /tmp/master
            echo "port 5000
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            $(cat /tmp/master)
            sentinel down-after-milliseconds master 5000
            sentinel failover-timeout master 60000
            sentinel parallel-syncs master 1
            sentinel auth-pass master $REDIS_PASSWORD
            " > /etc/redis/sentinel.conf
            cat /etc/redis/sentinel.conf
        envFrom:
        - secretRef:
            name: redis-password
            optional: false
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/